services:
  local-docker:
    build: .
    ports:
      - '3001:8080'
    env_file: .env.local
  real-prod:
    build: .
    ports:
      - '3002:8080'
    environment:
      VITE_APP_TITLE: 'This_has_been_replaced_in_runtime!'
      VITE_INITIAL_COUNT: 3
      VITE_ARTICLE_URL: https://medium.com/@yagelhayun/0f0169e6ab14
